spring:
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: create
  datasource:
    url: "jdbc:mysql://b159e03a0ce500:45f95f0f@us-cdbr-east-05.cleardb.net/heroku_b2879a69c8fab34?reconnect=true"
    driver-class-name: com.mysql.cj.jdbc.Driver
        
application:
  receitaws:
    uri: https://receitaws.com.br/v1/cnpj/%s
    
    #spring.datasource.driver-class-name=com.mysql.jdbc.Driver
 #spring.jpa.database-platform=org.hibernate.dialect.MySQL5InnoDBDialect